name: Jadhav-2016-Data-Analysis
channels:
- conda-forge
- defaults
dependencies:
- anaconda=custom=py35_0
- pandas=0.19.0
- pytest
- nitime
- tqdm
- dask
- jupyter=1.0.0=py35_3
- pytables=3.2.2=np111py35_4
- python=3.5.2=0
- scikit-image=0.12.3=np111py35_1
- seaborn=0.7.1=py35_0
- setuptools=23.0.0=py35_0
- statsmodels=0.6.1=np111py35_1
- xray=0.7.0=py35_0
- coveralls
- matplotlib
- icu=56.1
- pytest-cov
