name: Jadhav-2016-Data-Analysis
channels:
- conda-forge
- defaults
dependencies:
- anaconda
- pandas
- pytest
- nitime
- tqdm
- dask
- jupyter
- pytables
- python=3.5.2=0
- scikit-image
- seaborn
- setuptools
- statsmodels
- xray
- coveralls
- matplotlib
- icu=56.1
- pytest-cov
- numba
