name: Jadhav-2016-Data-Analysis
channels:
- conda-forge
- defaults
- edeno
dependencies:
- anaconda
- pandas
- pytest
- nitime
- tqdm
- dask
- jupyter
- nb_conda
- pytables
- "python>=3.5"
- scikit-image
- seaborn
- setuptools
- statsmodels
- xarray
- coveralls
- matplotlib
- icu=56.1
- pytest-cov
- numba
- snakeviz
- openblas
- replay_classification
- time_rescale
- ripple_detection
- loren_frank_data_processing
- spectral_connectivity
